services:
  - name: web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start

buildCommand:
  - npm install
  - npm run build

routes:
  - type: rewrite
    source: /
    destination: /index.html
